#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Filename:    plugin.py
# Description: Zigbee2MQTT Bridge — general zigbee2mqtt device integration for Indigo.
#              Auto-discovers all device types (lights, relays, sensors, covers) from
#              the zigbee2mqtt bridge and creates matching Indigo devices in a
#              "Zigbee2MQTT" device folder via Plugins > Discover & Create Devices.
# Author:      CliveS & Claude Opus 5
# Date:        14-08-2026
# Version:     2.3.0
#
# v2.3.0 (14-08-2026): MANAGED DEVICE SETTINGS. A device's firmware settings
# (sensitivity, delays, reporting intervals) live on the SENSOR, not in Indigo,
# so nothing owned them and nothing noticed when they changed. Two FP300s were
# set to AI-adaptive OFF on 24-Jun-2026 and were back ON by 06-Jul, inside a
# burst of power_outage_count increments — a battery change restoring the
# firmware defaults. They stayed wrong for FOUR WEEKS while bedroom presence
# fragmented nightly, with nothing logged.
# * Each device's config dialog now grows a Device Settings section, generated
#   from its own settable exposes, via getDeviceConfigUiXml — an UNDOCUMENTED
#   PluginBase hook (plugin_base.py:1240) whose default returns the static
#   ConfigUIRawXml. Any failure falls back to that default, because a device
#   that cannot open its dialog would be far worse than one without the section.
# * ONLY exposes with access & SET *and* access & PUBLISHED are managed. The
#   second half is load-bearing, not tidiness: without a readback we could
#   never tell drift from agreement, and it is what keeps us away from the
#   write-only entries, which are COMMANDS wearing a setting's clothes —
#   restart_device, spatial_learning, identify, and the FP300's 24
#   detection_range_N flags. Re-asserting restart_device on every reconnect
#   would reboot the sensor in a loop.
# * Drift is checked on the back of an INBOUND payload, which is the whole
#   trick: a battery sensor only accepts a write while awake and zigbee2mqtt
#   does not reliably queue one for a sleeping device, so a device that has
#   just published is the one moment a write is certain to land.
# * A null reading is NOT drift. zigbee2mqtt publishes nulls after a restart;
#   treating one as disagreement would fire a write off the back of no
#   information. Caught by a test, not by review.
#
# v2.2.0 (14-08-2026): the file split, and mains devices stop reporting a
# battery they do not have.
# * plugin.py 5,238 -> 1,219 lines. Constants, pure helpers and the
#   exposes-driven classifier became z2m_constants / z2m_helpers /
#   z2m_detection; the Plugin class is now composed from seven mixins
#   (actions, bridge, device states, menus, MQTT, native attributes, state
#   processing) with indigo.PluginBase LAST so a mixin still wins over its
#   defaults. All 115 methods present, each defined exactly once.
# * log() and the MQTT credentials are now LATE-BOUND through the module that
#   owns them. `from x import y` binds once at import, so patching one module
#   left the others calling the original — that broke 15 tests on the first
#   attempt and would have broken any future change the same silent way. The
#   tests now patch the owning module, which is more correct than what came
#   before, where patching plugin.py worked only because it was one file.
# * MAINS DEVICES: zigbee2mqtt reports power_source and the plugin ignored it,
#   so a mains device was seeded a battery state of 0 and showed a flat cell
#   for ever — absent presented as a reading. New devices no longer get the
#   state; an existing one cannot have it removed, so its 0 is labelled
#   "Mains". Unknown is NOT read as mains: hiding a genuinely flat cell is the
#   costlier mistake. Backfilled automatically when bridge/devices arrives,
#   which is the first moment the answer exists — deviceStartComm runs before
#   MQTT connects, so the cache is empty there. Live: 53 devices resolved,
#   15 mains.
#
# v2.1.1 (14-08-2026): added Contents/Resources/icon.png — the Plugin Store
# icon, one of the bundle pieces the official Developer's Guide expects and
# the only one this plugin had never had (the Resources folder did not exist).
# Generated by tools/make_icon.py so it can be rebuilt rather than only
# inherited.  The motif is a MESH, deliberately not the Zigbee logo, which is
# a registered trademark — and a mesh is the truer picture anyway, since this
# plugin surfaces routers and repeaters as well as the coordinator.
# No plugin logic changed.
#
# v2.1.0 (14-08-2026): the things Indigo
# itself already knows how to show, which this plugin was never telling it,
# plus the health topic that was arriving and being dropped.
# * NATIVE BATTERY. 38 battery-powered Zigbee devices reported into a custom
#   `battery` state and nothing else, so Indigo's own low-battery reporting,
#   dev.batteryLevel and every plugin reading it saw nothing at all — only the
#   11 Z-Wave devices had it estate-wide. The plugin now sets
#   SupportsBatteryLevel and mirrors the reading into the native attribute
#   from the same write, so the two can never disagree. The custom state is
#   KEPT because other plugins read it. An absent or unparseable reading is
#   left alone rather than written as 0 — a flat battery and a silent one are
#   different facts, and only one of them should raise an alert.
# * ERROR STATE. Nothing set dev.errorState when zigbee2mqtt reported a device
#   offline, so an offline Zigbee device looked perfectly healthy to the
#   Indigo UI and to DeviceHealthMonitor, which judges health by exactly that.
# * NATIVE ENERGY METER. Metering plugs never reached Indigo's Energy UI.
#   SupportsEnergyMeter / ...CurPower are now set and power/energy mirror into
#   curEnergyLevel / accumEnergyTotal. Energy Reset works properly: z2m's kWh
#   counter lives on the device and cannot be reset from here, so the reading
#   at the moment of reset is stored in energyResetOffset and the difference
#   reported — without that the next payload would silently undo the reset.
# * bridge/health INGESTED. Published every 10 minutes and previously dropped.
#   It is the only estate-wide evidence of a device rejoining or hopping
#   routing parent (leave_count / network_address_changes), which is the
#   answer to "why did that sensor go quiet". Coordinator devices gain the
#   z2m process and host stats; each device gains its own counters; and a new
#   "Report Network Health" menu item lists the troublemakers worst-first.
#   Counters are cumulative since z2m started, so a RISE is the signal — never
#   a non-zero value, which would fire every trigger in the house on startup.
# * CUSTOM TRIGGER EVENTS. The plugin shipped no Events.xml at all, so
#   reacting to a device joining, leaving or failing its interview needed a
#   script watching the log. Eleven events now come from bridge/event and
#   bridge/state. Bridge online/offline and restart-required fire on the
#   EDGE only, because both topics are retained and replay on every reconnect.
#
# v2.0.3 (08-08-2026): REQUIRED Info.plist KEY. `CFBundleURLTypes` was PRESENT but
# EMPTY, so the plugin shipped without the support URL that becomes its
# "About" menu item — one of the SIX keys the official Developer's Guide lists as
# required. An empty array satisfies "key exists" while giving users nowhere to go,
# which is why an earlier sweep that only looked for a MISSING key passed it. Found
# by an estate check auditing the VALUE rather than the key's presence.
# No plugin logic changed.
#
# v2.0.2 (21-07-2026): shared plugin_utils.py refreshed to v1.3 — the
# estate-wide propagation of the four Appliance Monitor deep-review fixes.
# * install_timestamp_filter() is idempotent — a second call used to stack a
#   second filter, so every log line came out with two timestamps.
# * `import indigo` is soft, so the module imports outside the Indigo host and
#   can be exercised by offline tests.
# * A malformed log call keeps its arguments in the log instead of dropping
#   them, so a %-placeholder mismatch is visible.
# * New shared as_bool() — a pref re-serialised as the string "false" is
#   truthy, which is exactly the wrong answer.
# This bundle's local duplicate-install guard is superseded by the shared one,
# and its child-logger note is folded into the shared comment.
#
# v2.0.0 (16-07-2026): paho-mqtt 1.6.1 -> 2.1.0 migration (the one deliberately
#   deferred structural item from the deep reviews). Isolated change:
#   * mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=...) — the
#     callback_api_version positional is REQUIRED in 2.x (without it the
#     client constructor raises and the bridge never connects).
#   * _on_mqtt_connect(client, userdata, flags, reason_code, properties) —
#     success is `not reason_code.is_failure`; the old int rc_labels dict is
#     DELETED (under VERSION2 even a 3.1.1 broker's CONNACK errors arrive as
#     MQTT-v5 ReasonCodes, e.g. bad credentials = 134 not 4, so the 1-5 keys
#     could never match again; str(ReasonCode) is already human-readable).
#   * _on_mqtt_disconnect(client, userdata, disconnect_flags, reason_code,
#     properties) — normalised at the boundary to {"rc": int, "reason": str}
#     so the main-thread route keeps its int semantics; the unexpected-
#     disconnect WARNING now includes the readable reason.
#   * on_message / on_connect_fail / username_pw_set / reconnect_delay_set /
#     connect_async / loop_start / loop_stop / disconnect: signature-identical
#     in 2.x — unchanged.
#   * The v1.9.14 liveness watchdog + v1.9.19 atomic rebuild carry over
#     UNCHANGED — verified to hold no 1.x assumptions (no flags dict access,
#     no is_connected, no internal-thread poking); 2.x improves some reconnect
#     edge cases but does not guarantee the half-open-socket wedge is gone.
#   * requirements.txt pin 2.1.0 with the migration recorded; tests use a
#     paho-free FakeReasonCode (conftest) so the suite still needs no
#     third-party packages. 4 callback call-sites updated.
# v1.10.0 (16-07-2026): Fable 5 deep-review feature batch (improvement lens).
#   * NEW z2mLock device type (relay class, Lock subtype): lock composites no
#     longer classify as relays sent ON/OFF — locks speak LOCK/UNLOCK, richer
#     lock_state enum in a custom state (not_fully_locked reads as unlocked),
#     onOffState ON = locked.
#   * NEW z2mThermostat device type (thermostat class): climate composites
#     (TRVs) get native temperatureInput1 / setpointHeat / hvacOperationMode
#     with actionControlThermostat (set/raise/lower heat setpoint, HVAC mode
#     heat/auto/off, status request), running_state + read-only valve
#     `position` in custom states, and a setpoint_key prop remembering whether
#     the device speaks current_ or occupied_heating_setpoint.
#   * NEW "Publish Custom Payload" device action — user JSON to /set for the
#     device options no typed action covers (validated at dialog save).
#   * NEW menu items: Test MQTT Connection (banner + live checks in one log
#     dump), Report Orphaned Devices (in Indigo but gone from z2m — report
#     only), Enable/Disable Pairing (permit_join to every configured bridge).
#   * z2m last_seen now surfaces as a readable `lastSeen` dynamic state
#     (handles both ms-epoch and ISO formats) instead of being swallowed.
#   * Connection diagnostics: paho's on_connect_fail is registered (an
#     unreachable broker was completely silent) and CONNACK failures (bad
#     credentials etc.) are reported once per outage instead of every retry.
#   * showPluginInfo gains liveness lines (last message age, queue depth,
#     silence limit) shared with the connection test via _banner_extras.
#   * Tests 597 -> 624 (+2 zoo rows: door_lock, trv reclassified from the
#     v1.9.21 sensor stopgap to z2mThermostat).
#   * NOT implemented (judged net-negative): a dynamic friendly-name menu in
#     device config — devices are auto-created (typing a name is the rare
#     path) and an empty-cache menu would BLOCK manual creation entirely.
# v1.9.23 (16-07-2026): Fable 5 deep-review batch 3 (lows + infos).
#   * wake_up reorders: MQTT reconnect BEFORE super() (device comm) so the
#     settle-delay /get requests no longer race a not-yet-connected client.
#   * stopConcurrentThread override REMOVED — it discarded the base class's
#     pipe-wake, making shutdown wait out the sleep interval.
#   * coordinator_map joins the maps_lock discipline at its last two unlocked
#     sites; new props_lock serialises pluginProps read-modify-write cycles
#     between the consumer thread and menu-thread refresh (deliberately held
#     across replacePluginPropsOnServer — an interleaved RMW silently drops
#     one side's changes); refresh now merges only its diff keys onto a fresh
#     read.
#   * _start_mqtt_locked stops an already-running client instead of orphaning
#     its network thread; on_connect uses a plain-string prefix snapshot (no
#     indigo.Dict reads on the paho thread); 'broker not configured' is INFO
#     not ERROR (estate convention).
#   * validatePrefsConfigUi validates mqtt_port + mqtt_silence_limit at the
#     dialog; _effective_port's prefs fallback logs a WARNING when invalid.
#   * _payload_bool sweep: contact/water_leak/motion-store handlers no longer
#     read string tokens ("false"/"OFF") as True.
#   * _brightness_255_to_100 rounds (readback matches the set level; z2m max
#     254 still reads 100); capability-gated /get (plain bulbs no longer make
#     z2m log errors for color/color_temp requests).
#   * Rename collision: a duplicate Indigo name no longer aborts the z2m
#     rename — props + routing follow z2m, Indigo name kept with a WARNING.
#   * _reclassify_as_button derives has_battery from current exposes (was
#     hardcoded False and never healed); z2mButton gains _DEVICE_STATE_DEFAULTS
#     + battery gate; z2mCover tiltAngle gated on has_tilt.
#   * _apply_updates logs the FIRST write failure per (device, state) at
#     WARNING (was debug-only silent data loss), repeats stay quiet.
#   * getDeviceStateList: dev.states=None at declaration time no longer
#     crashes the token-None fallback; dead _flatten_features removed;
#     colorMode gated on colour capability; repeaters reject on/off commands
#     with a WARNING instead of publishing them.
#   * plugin_utils.install_timestamp_filter gains a duplicate-install guard;
#     master IndigoSecrets template: MQTT_BROKER placeholder now "" (a truthy
#     placeholder beat the config dialog), MQTT section attributed, per-key
#     try/except import pattern documented.
#   * Tests 579 -> 597 (Actions.xml callbacks, not-connected paths, repeater
#     guard, warn-once, prefs validation, string tokens per handler, gated
#     /get); conftest dead code + stale fixture version cleaned; the
#     assertion-free JSON-stringify test now asserts.
# v1.9.22 (16-07-2026): Fable 5 deep-review batch 2 (mediums).
#   * Cross-bridge routing: friendly_name_map is now keyed by
#     (mqtt_prefix, friendly_name) — a name shared between the house and
#     garage bridges used to collide into one entry, bleeding one device's
#     state onto the other and blocking the second from ever being created.
#     All lookups (state routing, availability, creation exists-check,
#     capability-refresh fname fallback, rename/prefix-migration, reclassify)
#     are prefix-qualified; a prefix migration now moves the map key even
#     without a rename.
#   * Honest command logging: _publish returns True only when the message was
#     accepted by a live client (connected + rc==0); new _publish_cmd logs
#     'sent ...' on success and an ERROR naming the device on failure — the
#     action handlers no longer claim 'sent' for commands that died on a
#     disconnected/wedged client.
#   * Watchdog: two-stage liveness check — on silence it first PROBES
#     (bridge/request/devices, whose reply arrives on the existing
#     subscription) and only rebuilds if the probe is still unanswered at the
#     next tick, so a legitimately QUIET network (sparse install) no longer
#     triggers an endless rebuild cycle. Silence limit is now a guarded pref
#     (mqtt_silence_limit, min 60s, default 300).
#   * _hs_to_rgb: saturation divides by 100 not 255 — z2m publishes color_hs
#     saturation 0-100, so reported colours were capped at ~39% saturation.
#   * Discover & Create resilience: detection/props-build moved inside the
#     per-device try; malformed (non-dict) exposes entries skipped in
#     _detect_device_type, _should_reclassify_as_button and _iter_features —
#     one bad definition costs only itself, not the whole pass.
#   * deviceStartComm's settle-delay Timer is tracked per-device, daemonised,
#     and cancelled on deviceStopComm/shutdown (was fire-and-forget).
#   * smoke joined the capability system: has_smoke detection, seeded state
#     with gate (completes v1.9.21's semantic handling for existing devices).
#   * Tests 551 -> 579: cross-bridge collision suite, probe state machine,
#     publish honesty, saturation scale, first-ever coverage for
#     deviceStartComm happy path / didDeviceCommPropertyChange /
#     _ensure_device_states gating / refresh_device_capabilities; stub gained
#     opt-in strict state writes; the v1.9.9 reclassify test's indigo.device
#     replacement is now monkeypatched (no longer leaks) and its assertion
#     can no longer pass vacuously.
# v1.9.21 (16-07-2026): Fable 5 deep-review batch 1 (highs).
#   * HIGH classification: a device with an action enum AND an output capability
#     (switch composite or writable binary state) is now created as z2mRelay,
#     not z2mButton — decoupled-mode wall switches were losing on/off control
#     PERMANENTLY at Discover & Create (reclassify only converts toward button,
#     so nothing could heal it). Detection now mirrors the gates
#     _should_reclassify_as_button already enforced at runtime; the gate also
#     gained motion/pir alongside presence/occupancy (both places).
#   * HIGH data loss: the global _HANDLED_PAYLOAD_KEYS set claimed keys NO
#     handler wrote (smoke/vibration/tamper/voltage/current/battery_low were
#     blocked from dynamic capture yet never written — a smoke alarm produced
#     NO Indigo state change at all) and claimed keys globally that only some
#     types handle (a contact sensor's temperature, a bulb's power — silently
#     dropped). Replaced with per-type _HANDLED_KEYS_BY_TYPE +
#     _ALWAYS_CONSUMED_KEYS; everything a type's handler doesn't own is now
#     dynamically captured as a typed state.
#   * HIGH safety: smoke is handled semantically on z2mSensor — declared bool
#     `smoke` state + onOffState priority smoke > water_leak > occupancy >
#     contact, with _payload_bool guarding string tokens ("false" is False).
#   * Cover gate: a flat `position` feature only classifies as z2mCover when
#     WRITABLE and there is no climate composite — TRVs exposing a read-only
#     valve-position % were being created as blinds.
#   * Tests 474 -> 551: per-type capture, smoke semantics, classification gates,
#     reclassify map-repoint regression (v1.9.18 fix now locked in),
#     bridge/devices rename + prefix-migration + auto-create + flood-guard
#     paths, getDeviceStateList dynamic declarations (stub gained the
#     state-dict builders + an indigo.device create/delete shim), 6 new zoo rows.
#   * Companion: startup_z2m_check.py -> v1.6 (mosquitto alert debounce + storm
#     fix, subprocess timeouts, flock'd overlap guard, plugin-running check,
#     format-drift fallback, pgrep -x, main() wrapper).
# v1.9.20 (27-06-2026): deep-review batch 3 — cleared the entire deferred queue.
#   * #18 concurrency: friendly_name_map / ieee_map / coordinator_map are now
#     guarded by self.maps_lock (RLock) at every mutation site (deviceStartComm,
#     deviceStopComm, reclassify rebuilds, bridge/devices rename), so a
#     comprehension rebuild can't race a concurrent pop into a RuntimeError. Lock
#     held only for pure dict ops, never across an indigo.* call.
#   * #13: a dynamic payload field whose sanitised key collides with a static
#     Devices.xml state (e.g. snake-case `link_quality` -> `linkQuality`) is no
#     longer captured + written with a possibly-mismatched dynamic type
#     (_static_state_ids guard).
#   * #29: orphan dynamicKeyTypes entries are pruned in lock-step with
#     seenDynamicKeys (the two persisted stores no longer drift).
#   * #16: a dimmer reporting brightness 0 now forces onOffState off (some bulbs
#     publish {"state":"ON","brightness":0} during a fade-to-off).
#   * #17: the auto-reclassify-to-button trigger requires a NAMED action (one
#     carrying a letter), so a bare button-index "2" / junk can't drive a
#     destructive delete+recreate.
#   * #30: colour helpers round() instead of int() so a fully-saturated channel
#     reports 100, not 99.
#   * TEST SEAMS: runConcurrentThread's body extracted to _drain_queue with
#     per-message + liveness exception isolation (#23); +26 tests covering the
#     above plus the dispatch table (#8) and deviceStartComm config guards (#24).
#     Suite 448 -> 474. Bundled IndigoSecrets_example.py trimmed to the MQTT keys
#     this plugin actually uses (generic example IP).
# v1.9.19 (26-06-2026): deep-review batch 2 — medium correctness/robustness + polish.
#   * FIX (concurrency): MQTT teardown+rebuild is now atomic under one lock
#     (_rebuild_mqtt). The liveness watchdog and a concurrent config save can no
#     longer interleave a bare stop-then-start into leaking a second live paho
#     client that double-delivers every message.
#   * FIX (robustness): the catch-all z2mSensor handler tracks motion keys in the
#     per-device last-known store (like the occupancy handler) — a partial payload
#     no longer clears a still-present person on a mixed PIR+mmWave sensor.
#   * FIX (correctness): z2mButton lastAction enum expanded to the common
#     multi-function-remote vocabulary, and _normalise_action maps any unmapped
#     token to a declared "other" — actions that previously matched no Option (and
#     so vanished from the display + sub-states) now always surface.
#   * FIX (low): the device CREATE path now uses _compute_light_native_flags too,
#     so a CT-only bulb gets SupportsColor=True at creation (prereq for
#     SupportsWhiteTemperature) instead of only after a manual Refresh Capabilities
#     — v1.9.3 had fixed only the refresh path.
#   * POLISH: Refresh Device State action offered on every stateful device type
#     (was lights/relays/generic-sensor/covers only); dead has_voltage/has_current
#     relay gate entries removed; secrets-template Octopus annotation corrected.
#   * TEST: +20 (watchdog, paho ingress, connect/disconnect routes, atomic rebuild,
#     catch-all motion store, lastAction fallback, hs/port robustness) and the
#     light_ct zoo row now locks in the create-time SupportsColor fix. Suite 428 -> 448.
# v1.9.18 (26-06-2026): deep-review batch 1 — runtime reclassify guard + robustness.
#   * FIX (HIGH, data-loss): _should_reclassify_as_button now mirrors the v1.9.17
#     detection gate — a device exposing presence/occupancy is NEVER reclassified
#     as a button. An Aqara FP1 (RTCZCGQ11LM) emitting region `action` events was
#     being DELETED and recreated as a z2mButton at runtime (new id, every
#     trigger/link/control-page reference orphaned, presence states lost). The
#     detection fix alone never covered the runtime auto-reclassify path.
#   * FIX: _reclassify_as_button now also clears + repoints ieee_map (it was left
#     pointing at the deleted device id, breaking rename detection).
#   * ROBUSTNESS: wake_up resets last_rx_ts (watchdog no longer tears down the
#     just-reconnected client on Mac wake); _mqtt_liveness_check moved inside the
#     runConcurrentThread guard (a rebuild error can't kill the consumer thread);
#     _hs_to_rgb clamps hue/saturation (no negative RGB on a malformed payload);
#     _effective_port coerces a string MQTT_PORT from IndigoSecrets.
#   * TEST: +2 regression tests (presence/occupancy sensor with action must not
#     reclassify). Suite 426 -> 428.
# v1.9.17 (13-06-2026): device-type detection fix + device-zoo test layer.
#   * FIX: a device exposing BOTH `presence`/`occupancy` AND an `action` enum is
#     now classified as an occupancy sensor, not a button. The `action` enum on a
#     presence sensor carries region/presence events (enter/leave/occupied), not
#     scene-controller presses. Without the gate the Aqara FP1 (RTCZCGQ11LM) was
#     mis-detected as a z2mButton on Discover & Create — losing its presence
#     semantics. Real buttons (action, no presence/occupancy) are unaffected.
#     Found by the new device zoo running CliveS's real broker payloads.
#   * TEST: added tests/zoo_manifest.py + tests/test_zoo.py — a declarative
#     "device zoo" mapping each exposes payload to the full translation it must
#     yield (device type + capability props), parametrised, plus cross-cutting
#     invariants (pure-contact-never-motion, presence-never-button, battery never
#     dropped, colour-lesson Supports* set). Real captures live in tests/zoo_real/.
# v1.9.16 (10-06-2026): repo-audit hygiene release (no behaviour change for users).
#   * DEPENDENCY: colormath==3.0.0 removed from requirements.txt — unmaintained
#     since 2018 (SyntaxWarnings on Python 3.13) and pulled numpy (~40 MB) onto
#     every user install, all for one XY→RGB conversion. _xy_to_rgb is now pure
#     Python: same Wide-RGB-D65 matrix the fallback always used, plus
#     chromaticity-preserving peak scaling and the standard sRGB gamma encode so
#     reported colours stay close to what colormath produced. Install is now
#     paho-mqtt only.
#   * DISCIPLINE: _on_mqtt_connect called log() (an indigo.server.log) from the
#     paho thread, contradicting the section's own "queue only, no Indigo calls"
#     rule. The subscribed-topics list now rides the __connected__ queue message
#     and is logged on the main thread.
#   * ROBUSTNESS: bridge/devices and bridge/info payloads of an unexpected JSON
#     type were silently discarded; both now log a WARNING naming the type and
#     prefix so a misbehaving Z2M build is visible instead of just "no devices".
#   * NEW guard-rails: GitHub Actions CI runs the full pytest suite + ruff
#     (errors-only) on every push/PR; ruff.toml added; 4 lint errors fixed.
#
# v2.0.1 (21-07-2026): LOG-LEVEL FIX. indigo.server.log(level=...) wants a Python
# logging INT — a STRING is silently ignored and the line logs as plain Info.
# The log() helper passed its level name straight through, so every WARNING and
# ERROR raised through it had been appearing as an ordinary Info line. Added
# _lvl() to map the name to a real level. Estate-wide sweep (38 files).
#
# v1.9.15 (06-06-2026): deep-review fixes.
#   * HIGH: universal-action handler was named actionControlUniversalDevices — Indigo's
#     callback is actionControlUniversal (confirmed vs all SDK examples), so it was dead
#     code (everyday Send Status Request still worked via the class-specific handlers).
#     Renamed. (Global CLAUDE.md dispatch table corrected — it had the wrong name.)
#   * HIGH (script): startup_z2m_check.py Pushover used executeAction("sendMessage",
#     {title,message}) — wrong id + keys, so the watchdog's restart-failed alert never
#     sent. Fixed to "send" / msgTitle / msgBody / msgPriority / msgSound.
#   * MEDIUM (data-loss): _process_device_state reclassified ANY non-button device that
#     received an 'action' into a button — deleting + recreating it, destroying a real
#     dimmer/cover/switch-with-scenes and orphaning every trigger/link. New
#     _should_reclassify_as_button re-checks the device's CURRENT exposes and only
#     converts when there is no brightness/position/writable-state/light-cover-switch.
#   * MEDIUM: unguarded int()/float() in _process_light_state and the relay/cover
#     linkquality coercions dropped the WHOLE update batch on one malformed field; each
#     numeric block is now try/except-guarded (mirrors the contact/relay power handlers).
#
# v1.9.13 (28-05-2026): Dynamic state-type inference for captured z2m payload
# fields. Each dynamic key is tagged with a type token (bool/onoff/int/real/str)
# persisted in the new dynamicKeyTypes pluginProp, so getDeviceStateList declares
# it with the correct Indigo state type (BoolTrueFalse / BoolOnOff / Integer /
# Real / String) instead of declaring everything as String. The type is inferred
# when the raw value is in hand (in _capture_raw_fields) — getDeviceStateList
# runs at declaration time when dev.states is still None, so it reads the
# persisted token map rather than the (absent) value. Type drift (int then
# float) widens to Real; genuine disagreement falls back to String. Existing
# String states migrate to their proper type on the next payload that includes
# them. dynamicKeyTypes is excluded from didDeviceCommPropertyChange (cosmetic
# healing write, must not cycle comm). Reconciled from the stash that was parked
# alongside the v1.9.12 enum work so the two coexist cleanly.
#
# v1.9.12 (28-05-2026): z2mButton lastAction migrated from a plain String
# state to a List enumeration. Indigo now auto-generates per-value boolean
# sub-states (lastAction.single, lastAction.double, lastAction.hold, ...) so
# users can trigger on a specific action straight from the Triggers UI rather
# than writing an `if action == "double"` string compare. The raw z2m action
# is normalised before writing (the leading "<n>_" button-index prefix — kept
# separately in lastButton — is stripped and remaining underscore tokens are
# camelCased) so the value is a legal enum sub-state suffix: "1_single" ->
# "single", "brightness_move_up" -> "brightnessMoveUp". Existing button devices
# get a one-time stateListOrDisplayStateIdChanged() refresh in deviceStartComm.
#
# v1.9.14 (29-05-2026): Added an application-level MQTT liveness backstop. paho's
# loop_start auto-reconnect can wedge on a half-open socket after a network blip
# WITHOUT firing on_disconnect — leaving the client "connected" but deaf (this is
# what left Jane Lamp dead on 29-05-2026: "sent" published into a dead socket, zero
# inbound, lastSuccessfulComm frozen). runConcurrentThread now stamps last_rx_ts on
# every inbound message and rebuilds the client (_stop_mqtt + _start_mqtt) if nothing
# has arrived for MQTT_SILENCE_LIMIT (300s), independent of paho's own loop. Pairs
# with the estate-wide Device Health Monitor watchdog as defence-in-depth.
#
# v1.9.11 (27-05-2026): Added prepare_to_sleep / wake_up overrides
# harvested from the 27-May plugin_base.py sweep. Mac sleep used to leave
# Mosquitto holding our previous session as a stale ghost client until
# paho's keepalive fired (60s); on wake the bridge would just sit there
# until the Mac re-noticed the broker. Now MQTT disconnects cleanly on
# sleep, reconnects on wake.
#
# v1.9.9 (25-05-2026): Bug fix surfaced by new pytest suite —
# _reclassify_as_button used `self._ensure_device_folder()` with no
# argument, but the method requires `name`. Every reclassify of a
# device sitting at the root level (folderId=0) crashed with
# TypeError, leaving the device deleted but not recreated. Now passes
# DEVICE_FOLDER_NAME to match the other three call sites.
# Adds a ~226-test pytest suite under tests/ (no Indigo runtime needed)
# covering pure helpers, device-type detection, capability flags, state
# sanitiser, action dispatch (Dimmer/Sensor/Universal), state processing
# for every device class, MQTT topic routing, and bug-regression tests.
#
# v1.9.8 (25-05-2026): Added actionControlSensor() — sensor-class devices
# (z2mSensor, z2mContactSensor, z2mOccupancySensor, z2mWaterLeakSensor,
# z2mTemperatureSensor, z2mButton) had no handler, so any "Send Status
# Request" action against them logged
#   "plugin does not define method actionControlSensor"
# in the event log. New method handles indigo.kSensorAction.RequestStatus
# by re-publishing the z2m /get topic; all other sensor actions log a
# WARNING (sensors are read-only — no commands flow back to the network).
#
# v1.9.7 (23-05-2026): Millisecond timestamp [HH:MM:SS.mmm] prefix on every
# log line via plugin_utils.install_timestamp_filter() — matches Device
# Activity Monitor convention. Module-level log() helper bumped to ms.
# New "Toggle Timestamps in Log" menu item.
#
# v1.9.5 (22-05-2026):
# - Refactor from code-review pass (no behaviour change):
#   * Extracted `_compute_light_native_flags(has_color, has_color_temp)`
#     @staticmethod — single source of truth for SupportsColor / SupportsRGB /
#     SupportsWhite / SupportsWhiteTemperature. Both _apply_light_capabilities
#     (deviceStartComm path) and refresh_device_capabilities (menu path) now
#     call this helper, eliminating the flip-flop risk noted in v1.9.3.
#   * Unified the two diff-detection loops in refresh_device_capabilities
#     into a single pass over a merged `target` dict.
#   * Moved `_build_capabilities_display` call inside the `if diffs:` guard —
#     skips ~50 string-format calls per menu invocation on no-op refreshes.
#   * Pruned the 14-line contradictory comment above the displayStateId guard
#     in deviceStartComm; investigation history stays in the v1.9.4 changelog.
#
# v1.9.4 (22-05-2026):
# - deviceStartComm now logs a WARNING when an existing device's cached
#   displayStateId disagrees with the current Devices.xml <UiDisplayStateId>.
#   For z2mButton (lastAction) and z2mTemperatureSensor (temperature) the XML
#   value was updated in v1.8.0, but Indigo caches displayStateId on the
#   device record at create time — it is a read-only attribute on existing
#   devices and stateListOrDisplayStateIdChanged() does NOT update it.
#   Confirmed: assignment raises "the attribute \"displayStateId\" is read-only
#   on this instance". The only fix for an existing device is delete +
#   recreate via Plugins -> Discover & Create Devices. The new
#   _EXPECTED_DISPLAY_STATE map drives the per-device check and a clear
#   user-facing warning that names the affected devices.
#
# v1.9.3 (22-05-2026):
# - "Refresh Device Capabilities" now sets SupportsColor / SupportsRGB /
#   SupportsWhite / SupportsWhiteTemperature on z2mLight using the SAME formula
#   as _apply_light_capabilities (SupportsColor = has_color OR has_color_temp,
#   because CT-only bulbs need it as the prereq for SupportsWhiteTemperature).
#   v1.9.2 used create-time logic (SupportsColor = has_color alone) and so
#   downgraded CT-only Hue White Ambiance bulbs on first refresh; the
#   subsequent deviceStartComm would then re-set them, causing a flip-flop.
#
# v1.9.2 (22-05-2026):
# - New menu item "Refresh Device Capabilities" — walks every existing Z2M
#   Indigo device, looks it up in self.bridge_devices by ieee_address (then
#   friendly_name as fallback), re-runs the per-type _detect_*_capabilities()
#   against the live exposes, and merges any has_* / capabilities_display
#   changes via replacePluginPropsOnServer. Then re-applies _apply_indigo_subtype
#   so the catch-all z2mSensor subType backfill runs after the flags update.
#   Logs per-device diffs. Idempotent. Fixes devices created before Z2M had
#   emitted a full exposes definition (e.g. Aqara FP1 presence sensors, contact
#   sensors with empty has_* flags but real state values).
#
# v1.9.1 (22-05-2026):
# - z2mSensor catch-all now gets a backfilled Indigo subType. Devices created
#   before the v1.8.0 specific sensor types existed (z2mContactSensor /
#   z2mOccupancySensor / z2mTemperatureSensor) stayed on z2mSensor and so got
#   no subType — meaning HomeKitLink-Siri, control pages and Indigo's UI all
#   treated them as generic. _apply_indigo_subtype() now infers the correct
#   subType from the device's stored capability flags (has_contact / has_occupancy
#   / has_temperature etc.): pure-contact → DoorWindow, pure-occupancy → Motion,
#   pure-environmental → Temperature. Mixed-capability sensors stay unset
#   (they ARE genuinely generic). Device IDs are preserved — no triggers or
#   control pages break, unlike a delete-and-recreate migration.
#
# v1.9.0 (22-05-2026):
# - New z2mCoordinator custom device representing the Z2M bridge itself
#   (one per MQTT prefix — supports multi-bridge setups like CliveS's
#   zigbee2mqtt + zigbee2mqtt_garage). States: status, version, coordinator,
#   permitJoin, permitJoinEnd, networkChannel, panId, extendedPanId,
#   deviceCount, restartRequired, logLevel, lastUpdate. Populated from
#   prefix/bridge/state and prefix/bridge/info MQTT topics. deviceCount is
#   kept fresh from the existing bridge/devices cache.
# - New menu item "Create Coordinator Devices" — auto-creates one device
#   per configured prefix (primary + garage). Idempotent.
# - _on_mqtt_message now passes bare-string payloads through (older Z2M
#   bridge/state publishes "online" without JSON quotes) instead of dropping.
#
# v1.8.0 (22-05-2026):
# - Indigo device subType applied to every device type (was 0).  Lights,
#   relays, contacts, occupancy,
#   temperature sensors and covers now get the right SDK subType so
#   HomeKitLink-Siri, control pages and Indigo's UI render the right icon /
#   accessory kind.  Set statically in Devices.xml + dynamically in
#   _apply_indigo_subtype() (z2mLight → ColorDimmer vs Dimmer based on
#   has_color; also backfills devices created before 1.8.0).
# - UiDisplayStateId added to z2mTemperatureSensor (temperature) and z2mButton
#   (lastAction) so the device list shows the actually-useful state.
# - exception_handler() helper added — logs traceback PLUS the failing source
#   line and function name extracted from the deepest traceback frame.  Wired
#   into the high-traffic raw-field capture path and availability handler so
#   per-device failures finally name themselves.
#
# v1.7.2 (13-05-2026):
# - Secrets import split into per-key try/except blocks. Previous single-line
#   `from IndigoSecrets import MQTT_BROKER, MQTT_PORT, MQTT_USERNAME, MQTT_PASSWORD`
#   would fail entirely if any one key was missing, blanking all four. Now
#   each key falls back independently per CLAUDE.md secrets policy.
#
# v1.7 (10-05-2026):
# - Show only the entities each device actually supports.  Pre-init of default
#   states is now filtered by the device's `has_*` capability flags instead of
#   blindly seeding every state from Devices.xml.  Per the Indigo state-visibility
#   rule (memory: feedback_indigo_state_visibility.md), states that are never
#   written do not appear in the Custom States panel — so unused states are now
#   hidden automatically.
# - Capture ALL Z2M data: any MQTT payload field not handled by the type-
#   specific dispatcher is now imported as a dynamic Indigo state.  First time a
#   field is seen for a device, the state list is refreshed via
#   stateListOrDisplayStateIdChanged() and the device's seen-fields union is
#   persisted in pluginProps so they survive restarts.  getDeviceStateList() is
#   overridden to advertise the dynamic states to Indigo's state machinery.
# - Reserved-state guard: dynamic state names are mangled to avoid colliding
#   with native or reserved Indigo state IDs (batteryLevel, brightnessLevel etc).

import os as _os
import queue
import sys as _sys
import threading
import time

# ── Startup banner + secrets ─────────────────────────────────────────────────
_sys.path.insert(0, _os.getcwd())
try:
    from plugin_utils import log_startup_banner
except ImportError:
    log_startup_banner = None
try:
    from plugin_utils import install_timestamp_filter
except ImportError:
    install_timestamp_filter = None

# Credentials live in z2m_secrets.py from v2.2.0 so the MQTT mixin can read them
# without importing this file, which would be circular. Re-exported here because
# the resolution order (IndigoSecrets first, PluginConfig as fallback) is
# unchanged and other code in this file reads them.
from z2m_secrets import (            # noqa: F401
    MQTT_BROKER, MQTT_PASSWORD, MQTT_PORT, MQTT_USERNAME,
)

import indigo  # noqa: E402  (Indigo injects this at runtime)

# ── paho-mqtt (installed by Indigo from requirements.txt) ────────────────────
try:
    import paho.mqtt.client as mqtt
except ImportError:
    mqtt = None

# colormath was dropped in v1.9.16 — it was unmaintained (last release 2018,
# SyntaxWarnings on Python 3.13) and pulled numpy (~40 MB) onto every install,
# all for one XY→RGB conversion that _xy_to_rgb now does in pure Python with
# the standard sRGB matrix + gamma encode.

# ── Extracted modules (v2.2.0) ────────────────────────────────────────────────
# plugin.py had reached 5,238 lines. The constants, the pure helpers and the
# exposes-driven classifier are now their own modules; the Plugin class stays
# here.
#
# THESE IMPORTS DEPEND ON THE `_sys.path.insert(0, _os.getcwd())` ABOVE, and
# nothing here will tell you if that ever moves. At runtime Indigo sets cwd to
# this "Server Plugin" directory, and that insert is what puts it on sys.path —
# `__file__` is not defined inside a plugin host, so there is no other handle on
# it. The test suite CANNOT catch a reordering, because conftest.py adds the
# same directory to sys.path itself before importing this module: the tests
# would stay green while the plugin failed to start at all. Keep these imports
# below that insert.
#
# Everything is re-exported into this module's namespace deliberately, NOT as a
# tidiness afterthought: the test suite reaches for `plugin_mod._detect_device_type`
# and friends, and other code in this file uses them unqualified. Re-exporting
# keeps the split invisible to both.
from z2m_constants import (          # noqa: F401
    PLUGIN_ID, PLUGIN_NAME,
    RECONNECT_DELAY, MQTT_SILENCE_LIMIT, MQTT_WATCHDOG_EVERY,
    STATE_REQUEST_DELAY, DEVICE_FOLDER_NAME,
    _BUTTON_ACTION_VALUES, _ALWAYS_CONSUMED_KEYS, _HANDLED_KEYS_BY_TYPE,
    _HANDLED_KEYS_FALLBACK, _handled_keys_for, _RESERVED_STATE_NAMES,
)
import z2m_helpers                    # noqa: F401  (late-bound log, below)
from z2m_helpers import (            # noqa: F401
    _LOG_LEVELS, _lvl,
    _xy_to_rgb, _hs_to_rgb,
    _brightness_255_to_100, _brightness_100_to_255,
    _kelvin_to_mireds, _mireds_to_kelvin,
    _format_last_seen, _payload_bool, _iter_features,
)
from z2m_detection import (          # noqa: F401
    _detect_device_type,
    _detect_light_capabilities, _detect_contact_sensor_capabilities,
    _detect_occupancy_sensor_capabilities, _detect_water_leak_sensor_capabilities,
    _detect_temperature_sensor_capabilities, _detect_sensor_capabilities,
    _detect_relay_capabilities, _build_capabilities_display,
)


# Late-bound so z2m_helpers.log is the ONE place logging can be patched — see
# the same note in each mixin module.
def log(*args, **kwargs):
    # Transparent pass-through: forward EXACTLY what the caller passed. Naming
    # the parameters here would turn `log(msg)` into a two-positional call,
    # which silently breaks anything that patches log with a narrower
    # signature — and a patched logger that raises TypeError is a confusing
    # way to discover a refactor changed a call shape.
    return z2m_helpers.log(*args, **kwargs)


from z2m_actions import ActionsMixin
from z2m_bridge import BridgeMixin
from z2m_device_states import DeviceStatesMixin
from z2m_menus import MenusMixin
from z2m_mqtt import MqttMixin
from z2m_native import NativeAttributesMixin
from z2m_ota import OtaMixin
from z2m_settings import SettingsMixin
from z2m_state_processing import StateProcessingMixin


# ── Plugin ────────────────────────────────────────────────────────────────────

class Plugin(
    ActionsMixin,
    BridgeMixin,
    DeviceStatesMixin,
    MenusMixin,
    MqttMixin,
    NativeAttributesMixin,
    OtaMixin,
    SettingsMixin,
    StateProcessingMixin,
    indigo.PluginBase,
):
    # indigo.PluginBase is LAST on purpose. Python resolves left to right, so a
    # method defined in a mixin must win over PluginBase's default — putting
    # PluginBase first would silently restore every default this plugin
    # overrides, and nothing would raise.

    def __init__(self, pluginId, pluginDisplayName, pluginVersion, pluginPrefs):
        super().__init__(pluginId, pluginDisplayName, pluginVersion, pluginPrefs)

        self.pluginId          = pluginId
        self.pluginDisplayName = pluginDisplayName
        self.pluginVersion     = pluginVersion

        self.timestamp_enabled = bool(pluginPrefs.get("timestampEnabled", True))
        if install_timestamp_filter:
            self._ts_filter = install_timestamp_filter(self, enabled=self.timestamp_enabled)
        else:
            self._ts_filter = None

        self.debug = pluginPrefs.get("showDebugInfo", False)

        # MQTT state
        self.mqtt_client    = None
        self.mqtt_connected = False
        self.mqtt_lock      = threading.Lock()

        # Guards the device-lookup maps below (friendly_name_map / ieee_map /
        # coordinator_map). They are mutated by BOTH the Indigo lifecycle thread
        # (deviceStartComm / deviceStopComm) and the MQTT consumer thread
        # (reclassify rebuild + bridge/devices rename), so a comprehension rebuild
        # can otherwise race a concurrent pop into a RuntimeError. RLock so a guarded
        # method may nest. Held ONLY for pure dict ops — never across an indigo.* call.
        self.maps_lock      = threading.RLock()

        # Message queue (paho callback -> main thread via runConcurrentThread)
        self.msg_queue = queue.Queue()

        # MQTT liveness backstop — stamp of last inbound message + last watchdog check.
        self.last_rx_ts       = time.time()
        self._last_mqtt_check = 0.0
        # Outstanding liveness probe: ts of the bridge/request/devices probe the
        # watchdog sent to distinguish a wedged socket from a QUIET network.
        # 0.0 = no probe outstanding.
        self._probe_sent_ts   = 0.0

        # Per-device state-request timers (deviceStartComm's settle delay),
        # tracked so stop/shutdown can cancel them (v1.9.22 — an untracked
        # Timer could fire after its device was deleted or the plugin stopped).
        self._state_request_timers = {}  # type: dict[int, threading.Timer]

        # Plain-string prefix snapshot for the paho-thread on_connect callback
        # (set in _start_mqtt_locked — no indigo.Dict reads off-main-thread).
        self._subscribed_prefixes = ()

        # (dev.id, state_key) pairs whose write already failed once — the first
        # failure logs a WARNING, repeats stay at debug (see _apply_updates).
        self._state_write_warned = set()

        # Once-per-outage connect-failure reporting (v1.10.0): paho retries
        # forever, so unreachable-broker / bad-credential errors are reported
        # once per distinct condition and re-armed by a successful connect.
        self._connect_fail_reported = False
        self._last_connect_fail_msg = None

        # IEEE addresses of the bridges' own coordinator radios (v1.10.0).
        # bridge/devices entries of type Coordinator are deliberately excluded
        # from the device cache, so without this the orphan report flags the
        # coordinator radio's repeater tile as orphaned (live false positive:
        # the SLZB-06P7 house radio).
        self._coordinator_ieees = set()

        # Serialises pluginProps read-modify-write cycles (dict(dev.pluginProps)
        # -> mutate -> replacePluginPropsOnServer) between the MQTT consumer
        # thread (_capture_raw_fields, capability self-heal) and Indigo's
        # menu/UI threads (refresh_device_capabilities). Unlike maps_lock this
        # IS deliberately held across the replace call — that's the whole
        # point: two interleaved RMWs silently drop one side's changes
        # (v1.9.23). Menu ops are rare, so contention is negligible.
        self.props_lock = threading.RLock()

        # bridge/devices cache: ieee_address -> full device dict
        self.bridge_devices = {}     # type: dict[str, dict]

        # Active Indigo devices: (mqtt_prefix, friendly_name) -> indigo device id.
        # Prefix-qualified since v1.9.22: with two bridges (house + garage) a
        # friendly name shared across them used to collide into ONE entry —
        # both physical devices' payloads routed to a single Indigo device and
        # the second could never be auto-created.
        self.friendly_name_map = {}  # type: dict[tuple[str, str], int]

        # Active Indigo devices: ieee_address -> indigo device id
        # Used for O(1) rename detection when Z2M changes a friendly_name
        self.ieee_map = {}  # type: dict[str, int]

        # Tracks which non-primary prefixes have produced at least one MQTT message.
        # Used for diagnostic logging — fires once per prefix per session.
        self._seen_prefixes = set()  # type: set[str]

        # Coordinator devices: mqtt_prefix -> indigo device id (one per Z2M bridge)
        self.coordinator_map = {}  # type: dict[str, int]

        # Latest bridge/info payload per prefix (cached so menu items / refresh can
        # re-populate states without round-tripping MQTT).
        self._bridge_info_cache = {}  # type: dict[str, dict]

        # Latest bridge/state per prefix — cached because the retained MQTT message
        # may arrive before any coordinator device exists.  Replayed on
        # deviceStartComm so the freshly created device picks up online/offline.
        self._bridge_state_cache = {}  # type: dict[str, str]

        # Per-device motion component states for occupancy sensors.
        # Stores last known bool for each motion-related key the device has ever sent
        # (motion, occupancy, presence, pir, ...).  Partial payloads only update the
        # keys they contain, so the OR across all stored values is always correct.
        self._motion_states = {}  # type: dict[int, dict[str, bool]]

        # Last bridge/health per prefix: ieee -> {leave_count, network_address_changes}.
        # Held only to spot a RISE between reports; the counters themselves are
        # cumulative since zigbee2mqtt started, so their absolute value says
        # nothing about the last ten minutes.
        self._health_cache = {}  # type: dict[str, dict[str, dict]]

        # Enabled triggers of ours: trigger id -> trigger object.  Populated by
        # triggerStartProcessing; the only route to raising a plugin event.
        self.event_triggers = {}  # type: dict[int, object]

        # Bridge status last announced per prefix, so bridgeOnline / bridgeOffline
        # fire on a CHANGE rather than on every retained republish.
        self._bridge_status_announced = {}  # type: dict[str, str]

        # Last seen restart_required per prefix — same rising-edge reasoning.
        self._bridge_info_previous = {}  # type: dict[str, bool]

        # Startup banner moved to showPluginInfo on demand (revised 25-May-2026 per Jay).

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def startup(self):
        log(f"{PLUGIN_NAME} starting up")
        self._start_mqtt()

    def shutdown(self):
        log(f"{PLUGIN_NAME} shutting down")
        for dev_id in list(self._state_request_timers):
            self._cancel_state_request(dev_id)
        self._stop_mqtt()

    # ── Mac sleep / wake — disconnect MQTT cleanly on sleep so Mosquitto
    # ── doesn't hold the previous session as a stale ghost client. On wake
    # ── reconnect; retained messages will reseed device state.
    def prepare_to_sleep(self):
        log("Mac going to sleep — disconnecting from Mosquitto cleanly")
        self._stop_mqtt()
        super().prepare_to_sleep()
    prepareToSleep = prepare_to_sleep

    def wake_up(self):
        log("Mac woke — reconnecting to Mosquitto")
        # Give the fresh connection a full silence window, otherwise the liveness
        # watchdog sees the pre-sleep last_rx_ts (potentially hours old) and tears
        # the just-rebuilt client straight back down on the next check.
        self.last_rx_ts = time.time()
        # MQTT FIRST, then super() (which restarts device comm): the settle-delay
        # /get requests deviceStartComm schedules used to race the reconnect and
        # die on a not-yet-connected client (v1.9.23).
        self._start_mqtt()
        super().wake_up()
    wakeUp = wake_up

    def runConcurrentThread(self):
        """Drain the MQTT message queue on the Indigo main thread."""
        while True:
            self._drain_queue()
            self.sleep(0.2)

    def _drain_queue(self):
        """One consumer pass: process every queued MQTT message, then run the
        liveness check. Each message AND the liveness check are isolated so one
        bad item logs-and-continues instead of killing the only consumer thread
        (which would silently stop all device updates — the failure the watchdog
        exists to prevent). Extracted from runConcurrentThread as a test seam."""
        while not self.msg_queue.empty():
            try:
                topic, payload = self.msg_queue.get_nowait()
            except queue.Empty:
                break
            try:
                self._process_message(topic, payload)
            except Exception as e:
                log(f"error processing message {topic!r}: {e}", level="ERROR")
        try:
            self._mqtt_liveness_check()
        except Exception as e:
            log(f"liveness check error: {e}", level="ERROR")

    # NB: no stopConcurrentThread override — the base implementation sets
    # stopThread AND writes the wake pipe so self.sleep() returns instantly.
    # The old `self.stopThread = True` override discarded that pipe-wake and
    # made shutdown wait out the sleep interval (removed v1.9.23).

    # ── Plugin preferences ────────────────────────────────────────────────────

    def validatePrefsConfigUi(self, valuesDict):
        errors = indigo.Dict()
        prefix = valuesDict.get("mqtt_topic_prefix", "").strip()
        if not prefix:
            errors["mqtt_topic_prefix"] = "Topic prefix is required."
        # Numeric fields: catch bad values AT THE DIALOG instead of silently
        # falling back at runtime (v1.9.23).
        port_raw = str(valuesDict.get("mqtt_port", "")).strip()
        if port_raw:
            try:
                port = int(port_raw)
                if not (1 <= port <= 65535):
                    raise ValueError
            except (TypeError, ValueError):
                errors["mqtt_port"] = "Port must be a number between 1 and 65535."
        limit_raw = str(valuesDict.get("mqtt_silence_limit", "")).strip()
        if limit_raw:
            try:
                if int(limit_raw) < 60:
                    raise ValueError
            except (TypeError, ValueError):
                errors["mqtt_silence_limit"] = ("Silence limit must be a number "
                                                "of seconds, 60 or more.")
        return (len(errors) == 0), valuesDict, errors

    def closedPrefsConfigUi(self, valuesDict, userCancelled):
        if not userCancelled:
            self.debug = valuesDict.get("showDebugInfo", False)
            log("Preferences saved — reconnecting MQTT")
            # Atomic rebuild under one lock — a config save must not race the
            # liveness watchdog into leaking a second paho client.
            self._rebuild_mqtt()

    # ── Device lifecycle ──────────────────────────────────────────────────────

    def deviceStartComm(self, dev):
        # Coordinator devices have no friendly_name — they're indexed by mqtt_prefix
        if dev.deviceTypeId == "z2mCoordinator":
            prefix = dev.pluginProps.get("mqtt_prefix", "").strip()
            if not prefix:
                log(f"Coordinator '{dev.name}' has no mqtt_prefix — skipping",
                    level="WARNING")
                return
            with self.maps_lock:
                self.coordinator_map[prefix] = dev.id
            # v2.1.0 added the health and lastEvent states — register them
            # before anything tries to write one.
            dev = self._refresh_state_list_if_missing(
                dev, self._V210_COORDINATOR_STATES)
            self._ensure_device_states(dev)
            # If we already have a cached bridge/info or bridge/state for this
            # prefix (retained MQTT may have arrived before this device existed),
            # push them now so the device populates immediately.
            cached_info = self._bridge_info_cache.get(prefix)
            if cached_info:
                self._process_bridge_info(cached_info, prefix)
            cached_state = self._bridge_state_cache.get(prefix)
            if cached_state:
                self._update_coordinator(prefix, status=cached_state)
            # Backfill deviceCount from current cache
            count = sum(1 for d in self.bridge_devices.values()
                        if d.get("_mqtt_prefix") == prefix)
            if count:
                dev.updateStateOnServer("deviceCount", value=count)
            if self.debug:
                log(f"Started coordinator: {dev.name} (prefix={prefix})")
            return

        props = dev.pluginProps
        fname = props.get("friendly_name", "").strip()
        if not fname:
            log(f"Device '{dev.name}' has no friendly_name — skipping", level="WARNING")
            return

        ieee = props.get("ieee_address", "")
        with self.maps_lock:
            self.friendly_name_map[(self._device_prefix(dev), fname)] = dev.id
            if ieee:
                self.ieee_map[ieee] = dev.id

        # Apply Indigo subType — dynamic for lights (Dimmer vs ColorDimmer);
        # static for everything else.  Also backfills devices created before
        # subType was declared in Devices.xml.
        self._apply_indigo_subtype(dev)

        # Apply stored color/capability flags to Indigo device
        if dev.deviceTypeId == "z2mLight":
            self._apply_light_capabilities(dev)

        # Backfill the native attributes from what the device already holds, so
        # an existing install populates at restart rather than waiting hours for
        # each battery device's next report (v2.1.0).
        self._backfill_native_attributes(dev)

        # v2.1.0 added the per-device network-health counters — register them
        # before bridge/health arrives, or every write is refused server-side.
        dev = self._refresh_state_list_if_missing(dev, self._V210_HEALTH_STATES)

        # Ensure all custom states exist — guards against states added to Devices.xml
        # after a device was originally created (avoids "state key not defined" errors)
        self._ensure_device_states(dev)

        # displayStateId is cached on the device record at create time and is
        # read-only on existing instances — only fix for a stale value after a
        # <UiDisplayStateId> change in Devices.xml is delete + recreate.
        expected_display = self._EXPECTED_DISPLAY_STATE.get(dev.deviceTypeId)
        if expected_display and dev.displayStateId != expected_display:
            log(f"{dev.name}: displayStateId is {dev.displayStateId!r} but XML "
                f"now declares {expected_display!r} — delete + recreate this "
                f"device to pick up the new primary display state",
                level="WARNING")

        # v1.9.12 one-time migration: lastAction became a List enumeration, so
        # Indigo now auto-generates lastAction.<value> boolean sub-states. A
        # device created before the change keeps its old (String) cached state
        # list until we refresh it. Detect by the absence of a known sub-state:
        # stateListOrDisplayStateIdChanged() surfaces the sub-states and they
        # persist on the device record, so this skips on subsequent starts.
        # (A guard pluginProp is NOT used — replacePluginPropsOnServer during
        # deviceStartComm doesn't reliably persist.)
        if dev.deviceTypeId == "z2mButton" and "lastAction.single" not in dev.states:
            try:
                dev.stateListOrDisplayStateIdChanged()
                log(f"{dev.name}: migrated lastAction to enumeration — per-action "
                    f"sub-states (lastAction.single/.double/.hold/...) now "
                    f"available; the matching one goes true on the next press")
            except Exception as e:
                log(f"{dev.name}: lastAction enum state-list refresh failed: {e}",
                    level="WARNING")

        if self.debug:
            log(f"Started device: {dev.name} (type={dev.deviceTypeId}, name={fname})")

        # Request current state after brief delay (MQTT needs time to settle)
        prefix = self._device_prefix(dev)
        self._schedule_state_request(dev.id, fname, dev.deviceTypeId, prefix,
                                     dev_props=dict(dev.pluginProps))

    def _schedule_state_request(self, dev_id, fname, device_type_id, prefix,
                                dev_props=None):
        """Ask the device for its state after a short settle delay. Timers are
        daemonised and tracked per-device so deviceStopComm/shutdown can cancel
        them — an untracked Timer could fire after the device was deleted or
        the plugin stopped (v1.9.22; also the deviceStartComm test seam).
        dev_props is a plain-dict snapshot for the capability-gated /get —
        the Timer thread must not read live indigo objects."""
        self._cancel_state_request(dev_id)
        t = threading.Timer(STATE_REQUEST_DELAY, self._request_state,
                            args=(fname, device_type_id, prefix, dev_props))
        t.daemon = True
        self._state_request_timers[dev_id] = t
        t.start()

    def _cancel_state_request(self, dev_id):
        t = self._state_request_timers.pop(dev_id, None)
        if t is not None:
            t.cancel()






    # ── Auto-create helpers ───────────────────────────────────────────────────

    def _ensure_device_folder(self, name):
        """Return id of named device folder, creating it if absent."""
        for folder in indigo.devices.folders:
            if folder.name == name:
                return folder.id
        new_folder = indigo.devices.folder.create(name)
        log(f"Created device folder: '{name}'")
        return new_folder.id

    def _build_plugin_props(self, device_type_id, device_data, definition, exposes):
        """Build the pluginProps dict for a new auto-created device."""
        props = {
            "friendly_name":         device_data.get("friendly_name", ""),
            "ieee_address":          device_data.get("ieee_address", ""),
            "vendor":                definition.get("vendor", ""),
            "model":                 definition.get("model", ""),
            # zigbee2mqtt tells us how the device is powered ("Battery",
            # "Mains (single phase)", or absent). Stored so a mains device is
            # never given a battery state it can only ever report as 0 —
            # which reads as a flat cell rather than as "no battery here".
            "power_source":          device_data.get("power_source") or "",
        }

        if device_type_id == "z2mLight":
            caps = _detect_light_capabilities(exposes)
            props.update(caps)
            # Single source of truth for the native colour flags — must match
            # _apply_light_capabilities / Refresh Capabilities. SupportsColor is
            # has_color OR has_color_temp: a CT-only bulb needs it as the prereq for
            # SupportsWhiteTemperature, else Indigo silently ignores CT. The old
            # create-time logic (SupportsColor = has_color alone, and no
            # SupportsWhite) created CT-only bulbs unable to do colour temp until a
            # manual Refresh Capabilities — v1.9.3 fixed the refresh path but not
            # this create path.
            props.update(self._compute_light_native_flags(caps["has_color"],
                                                          caps["has_color_temp"]))

        elif device_type_id == "z2mContactSensor":
            caps = _detect_contact_sensor_capabilities(exposes)
            props.update(caps)

        elif device_type_id == "z2mOccupancySensor":
            caps = _detect_occupancy_sensor_capabilities(exposes)
            props.update(caps)

        elif device_type_id == "z2mWaterLeakSensor":
            caps = _detect_water_leak_sensor_capabilities(exposes)
            props.update(caps)

        elif device_type_id == "z2mTemperatureSensor":
            caps = _detect_temperature_sensor_capabilities(exposes)
            props.update(caps)

        elif device_type_id == "z2mSensor":
            caps = _detect_sensor_capabilities(exposes)
            props.update(caps)

        elif device_type_id == "z2mRelay":
            caps = _detect_relay_capabilities(exposes)
            props.update(caps)

        elif device_type_id == "z2mRepeater":
            caps = {}  # no sensor capabilities — availability + linkQuality only

        elif device_type_id == "z2mCover":
            names = {feat.get("name") for feat in _iter_features(exposes)}
            caps  = {"has_tilt": "tilt" in names}
            props.update(caps)

        elif device_type_id == "z2mButton":
            names = {feat.get("name") for feat in _iter_features(exposes)}
            caps  = {"has_battery": "battery" in names}
            props.update(caps)

        elif device_type_id == "z2mLock":
            names = {feat.get("name") for feat in _iter_features(exposes)}
            caps  = {"has_battery": "battery" in names}
            props.update(caps)

        elif device_type_id == "z2mThermostat":
            names = {feat.get("name") for feat in _iter_features(exposes)}
            caps  = {"has_battery": "battery" in names}
            props.update(caps)
            # Some TRVs expose occupied_heating_setpoint instead of
            # current_heating_setpoint — remember which one to publish to.
            props["setpoint_key"] = ("occupied_heating_setpoint"
                                     if ("occupied_heating_setpoint" in names
                                         and "current_heating_setpoint" not in names)
                                     else "current_heating_setpoint")
            # Native thermostat behaviour flags (heat-only TRV).
            props.update({
                "NumTemperatureInputs":       1,
                "NumHumidityInputs":          0,
                "SupportsHeatSetpoint":       True,
                "SupportsCoolSetpoint":       False,
                "SupportsHvacOperationMode":  "system_mode" in names,
                "SupportsHvacFanMode":        False,
                "ShowCoolHeatEquipmentStateUI": False,
            })

        else:
            caps = {}

        props["capabilities_display"] = _build_capabilities_display(device_type_id, props)
        return props

    # ── Light capability helpers ──────────────────────────────────────────────

    def exception_handler(self, exc, log_failing_statement=False, context=""):
        """Log an exception with full traceback. When log_failing_statement is
        True, also extract the actual source line that raised from the deepest
        traceback frame — invaluable when one device out of dozens triggers a
        failure and the bare message doesn't say which line in which method
        blew up.
        """
        import traceback
        tb = exc.__traceback__
        last_frame = None
        while tb is not None:
            last_frame = tb
            tb = tb.tb_next
        prefix = f"{context}: " if context else ""
        log(f"{prefix}{type(exc).__name__}: {exc}", level="ERROR")
        if log_failing_statement and last_frame is not None:
            fname    = last_frame.tb_frame.f_code.co_filename
            lineno   = last_frame.tb_lineno
            funcname = last_frame.tb_frame.f_code.co_name
            try:
                # encoding="utf-8" — Indigo's open() defaults to ASCII and
                # plugin source contains em-dashes (CLAUDE.md gotcha)
                with open(fname, encoding="utf-8") as f:
                    src_line = f.readlines()[lineno - 1].strip()
            except Exception:
                src_line = "(source unavailable)"
            short = fname.rsplit("/", 1)[-1]
            log(f"  at {short}:{lineno} in {funcname}() -> {src_line}", level="ERROR")
        log(traceback.format_exc(), level="ERROR")

    def _apply_indigo_subtype(self, dev):
        """Set dev.subType so Indigo, HomeKitLink-Siri and control pages get the
        right semantic class (icon + accessory kind). Dynamic for lights (colour
        capability) and for z2mSensor catch-all (inferred from capability flags).
        Static for everything else. Skips devices without a clean SDK match
        (z2mWaterLeakSensor, z2mRepeater, z2mButton, and mixed-capability z2mSensor).
        """
        target = None
        type_id = dev.deviceTypeId

        if type_id == "z2mLight":
            has_col = dev.pluginProps.get("has_color", False)
            target = (indigo.kDimmerDeviceSubType.ColorDimmer if has_col
                      else indigo.kDimmerDeviceSubType.Dimmer)
        elif type_id == "z2mRelay":
            target = indigo.kRelayDeviceSubType.Outlet
        elif type_id == "z2mContactSensor":
            target = indigo.kSensorDeviceSubType.DoorWindow
        elif type_id == "z2mOccupancySensor":
            target = indigo.kSensorDeviceSubType.Motion
        elif type_id == "z2mTemperatureSensor":
            target = indigo.kSensorDeviceSubType.Temperature
        elif type_id == "z2mCover":
            target = indigo.kDimmerDeviceSubType.Blind
        elif type_id == "z2mSensor":
            # Backfill: devices created before the specific sensor types existed
            # are still on the catch-all but their capability flags reveal which
            # specific subType they would have got under the v1.8.0 classifier.
            # Setting subType in place keeps the deviceId intact (no trigger /
            # control page breakage) while giving HomeKitLink-Siri the right
            # accessory routing. Mixed-capability sensors get no subType.
            props        = dev.pluginProps
            has_contact  = props.get("has_contact",    False)
            has_occ      = props.get("has_occupancy",  False)
            has_leak     = props.get("has_water_leak", False)
            has_env      = (props.get("has_temperature", False)
                            or props.get("has_humidity",    False)
                            or props.get("has_pressure",    False)
                            or props.get("has_illuminance", False))
            if has_contact and not has_occ and not has_leak:
                target = indigo.kSensorDeviceSubType.DoorWindow
            elif has_occ and not has_contact and not has_leak:
                target = indigo.kSensorDeviceSubType.Motion
            elif has_env and not has_contact and not has_occ and not has_leak:
                target = indigo.kSensorDeviceSubType.Temperature

        if target is not None and dev.subType != target:
            dev.subType = target
            dev.replaceOnServer()

    @staticmethod
    def _compute_light_native_flags(has_color, has_color_temp):
        # SupportsColor must be True for any lamp with colour OR CT — it's the
        # top-level prerequisite for both SupportsRGB and SupportsWhiteTemperature.
        # A CT-only bulb still needs SupportsColor=True or Indigo silently ignores
        # SupportsWhiteTemperature.
        return {
            "SupportsColor":            has_color or has_color_temp,
            "SupportsRGB":              has_color,
            "SupportsWhite":            has_color_temp,
            "SupportsWhiteTemperature": has_color_temp,
        }

    def _apply_light_capabilities(self, dev):
        """Set Indigo color capability flags from stored pluginProps (z2mLight only)."""
        props   = dev.pluginProps
        has_col = props.get("has_color",      False)
        has_ct  = props.get("has_color_temp", False)

        # If both flags are absent pluginProps is likely empty/unreadable — skip to
        # avoid clobbering existing capability flags with False values.
        if not has_col and not has_ct:
            return

        # Always call replacePluginPropsOnServer when capability data is present.
        # Indigo only propagates native attributes to the device via this call.
        with self.props_lock:   # atomic RMW vs the other props writers
            new_props = dict(dev.pluginProps)
            new_props.update(self._compute_light_native_flags(has_col, has_ct))
            dev.replacePluginPropsOnServer(new_props)

